namespace Astronauts.Core.DTOs;

public class AstronautDto
{
    /// <summary>
    /// Autogenerated id for Astronaut entity
    /// </summary>
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Nationality { get; set; }
    public string? Description { get; set; }
    public DateTime BirthDate { get; set; }
    public bool Status { get; set; }
    public byte[]? Photo { get; set; } = null;
}
